apiVersion: v1
kind: Service
metadata:
  labels:
    app: sctp-tunnel
  name: sctp-tunnel
spec:
  type: NodePort
  selector:
    app: sctp-tunnel
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 31358
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sctp-tunnel
  labels:
    app: sctp-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sctp-tunnel
  template:
    metadata:
      labels:
        app: sctp-tunnel
    spec:
      containers:
        - name: sctp-tunnel
          image: notexactlyawe/sctp_tunnel
          ports:
            - containerPort: 5000
          env:
            - name: SCTP_IP
              value: "oai-mme.oai"
            - name: SCTP_PORT
              value: "36412"
